repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt-local
        description: 'Format Python code'
        language: system
        types: [python]
        entry: make fmt
        pass_filenames: false
      - id: lint
        name: lint-local
        description: 'Lint Python code'
        language: system
        types: [python]
        entry: make lint
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v4.0.1
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '(?:.*/)?\.bumpversion\.cfg$'
      - id: trailing-whitespace
        exclude: '(?:.*/)?\.bumpversion\.cfg$'
